config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
    }
  resources :splash, only: [:index]
  resources :home, only: [:index, :update]
  resources :users do
    resources :runs
    resources :goals
  end

  devise_scope :user do
   get '/sign_up/:goal_id', to: 'registrations#new', as: :new_invite
  end
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user
  belongs_to :goal

  validates_presence_of :date
  validates_presence_of :total_distance
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  def index
    @user ||= User.find(params[:user_id])
    @runs ||= @user.runs.order(:date).reverse_order.paginate(:page => params[:page], :per_page => 6)
  end

  def show
    @run = Run.find(params[:id])

  end

  def new
    @user = current_user
    @run = @user.runs.new
  end

  def create
    @user = current_user
    @run = @user.runs.new(run_params)

    if @run.save
      current_race = Race.where(goal_id: @run.goal_id, user_id: @user.id ).first
      new_progress = current_race.progress.to_i + @run.total_distance.to_i
      current_race.update({progress: new_progress})
      redirect_to user_runs_path(current_user)
    else
      flash[:alert] = @run.errors.full_messages.each {|m| m.to_s}.join
      render :new
    end
  end

  def edit
    @user = current_user
    @run = Run.find(params[:id])
  end

  def update
    @user = current_user
    @run = Run.find(params[:id])
    if @run.update(run_params)
      @race = @user.races.new(goal_id: @run.goal_id, progress: @run.total_distance.to_i)
      if @race.save
        flash[:notice] = "You're on your way to a new goal"
      else
        current_race = Race.where(goal_id: @run.goal_id, user_id: @user.id ).first
        new_progress = current_race.progress.to_i + @run.total_distance.to_i
        current_race.update({progress: new_progress})
      end

      redirect_to user_goal_path(current_user, @run.goal)
    else
      flash[:alert] = @run.errors.full_messages.each {|m| m.to_s}.join
      render :edit
    end
  end

  def destroy
    @user = current_user
    @run = Run.find(params[:id])
    @run.destroy
    flash[:notice] = "You deleted your run"
    redirect_to user_runs_path(current_user)
  end

  private

  def run_params
    params.require(:run).permit(:start_location, :end_location, :total_time, :total_distance, :travel_method, :goal_id, :date)
  end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.slim
.card.grey.lighten-4
  .card-content.black-text
    = form_for [@user, @run] do |f|
      = f.label "total distance in METERS"
      = f.text_field :total_distance


      = f.label "total time in seconds"
      = f.text_field :total_time

      = f.label :date
      = f.date_field :date

      = f.label :travel_method
      = f.text_field :travel_method


      = f.label :goal_id
      = f.select :goal_id, @user.goals.collect{|goal| [goal.name, goal.id]}, id: 'run-select'
      = f.submit class: 'btn'

javascript:
  $(document).ready(function(){
    $('select').material_select();
  });

app/views/runs/_goals_form.html.erb
<%= form_for [@user, @goal] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :start_location %>
  <%= f.text_field :start_location %>

  <%= f.label :end_location %>
  <%= f.text_field :end_location %>

  <%= f.label :total_distance %>
  <%= f.text_field :total_distance %>

  <%= f.submit %>
<% end %>

app/views/runs/_run_card.html.erb.html.erb
<% @runs.order(date: :desc).each do |run| %>
    <div class="col l4 m6 s12">
      <div class="card grey lighten-4">
        <div class="card-content center black-text">
          <span class="card-title">Distance: <%= convert_meters_to_miles(run.total_distance, 1) %> miles <br> Date: <%= display_date(run.date) %></span>
          <hr>
          <p>Time: <%= convert_seconds(run.total_time, "minutes") %> minutes</p>
          <p>Avg Speed: <%= (convert_seconds(run.total_time, "minutes")/convert_meters_to_miles(run.total_distance, 4)).round(2) %> minutes per mile</p>
          <p>Travel Method: <%= run.travel_method %> </p>
          <br>
          <div class="run-goal">
            <% if run.goal %>
              <strong><p>Goal: <%= link_to run.goal.name, user_goal_path(@user, run.goal) %></p></strong>
                <div class="progress">
                  <div class="progress-bar" style="width: <%= width =calc_percent(@user, run.goal) %>" id="<%= progress_color(width) %>"></div>
                </div>
            <% elsif run.user == current_user %>
              <%= render 'runs/selector', run: run %>
            <% else %>
              <p>Not yet assigned to a goal</p>
            <% end %>
          </div>
        </div>
        <div class="card-action center">
          <%= link_to "view", user_run_path(current_user, run) %>
          <% if current_user && current_user == @user %>
            <%= link_to "edit", edit_user_run_path(current_user, run) %>
            <%= link_to "delete", user_run_path(current_user, run), :data => {confirm: 'Are you sure you want to delete this run?', method: 'delete'} %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

app/views/runs/_run_card.slim
- @runs.each do |run|
  .col.l4.m6.s12
    .card.grey.lighten-4
      .card-content.center.black-text
        span.card-title
          | Distance:&nbsp
          = convert_meters_to_miles(run.total_distance, 1)
          |  miles
          br
        	br
          | Date:&nbsp
          = display_date(run.date)
        hr
        p
          | Time:&nbsp
          = convert_seconds(run.total_time, "minutes")
          |  minutes
        p
          |Avg Speed:&nbsp
          = (convert_seconds(run.total_time, "minutes")/convert_meters_to_miles(run.total_distance, 4)).round(2)
          |  minutes per mile
        p
          | Travel Method:&nbsp
          = run.travel_method
        br
        .run-goal
          - if run.goal
            p.strong
              |Goal:&nbsp
              = link_to run.goal.name, user_goal_path(@user, run.goal)
              .progress
                <div class="progress-bar" style="width: #{width =calc_percent(@user, run.goal)}" id="#{ progress_color(width) }">
                </div>
          - elsif run.user == current_user
            = render 'runs/selector', run: run
          - else
            p Not yet assigned to a goal

      .card-action.center
        - if current_user && current_user == @user
          = link_to "edit", edit_user_run_path(current_user, run)
          = link_to "delete", user_run_path(current_user, run), :data => {confirm: 'Are you sure you want to delete this run?', method: 'delete'}

app/views/runs/_run_map.html.erb
<div class="map-container">
  <div id="map">
  </div>
</div>

<script>
      var map;
      function initMap() {
        var start = {lat: <%= @run.start_latlng[0] %>, lng: <%= @run.start_latlng[1] %>};
        var end = {lat: <%= @run.end_latlng[0] %>, lng: <%= @run.end_latlng[1] %>};


        map = new google.maps.Map(document.getElementById('map'), {
          center: start,
          zoom: 12
        });
        var start_marker = new google.maps.Marker({
          position: start,
          map: map
        });
        var end_marker = new google.maps.Marker({
          position: end,
          map: map
        });
      }
</script>

app/views/runs/_selector.slim
= form_for [@user, run] do |f|
  = f.label "Select a goal to assign these miles"
  = f.select(:goal_id, @user.goals.collect{|goal| [goal.name, goal.id]})

javascript:
  $(document).ready(function(){
    $('select').material_select();
  });
    $(document).on("turbolinks:load", function(){
      $('form').on("change", "select", function(){
        $(this).parent().parent('form').submit();
      });
    });

app/views/runs/edit.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <h3>Edit your run</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/runs/index.slim
h3.center
  = @user.name
  |'s
  |  runs
- if @user == current_user
  = link_to 'Add a Run', new_user_run_path(current_user), class: 'btn right-align'
.row
  = render 'run_card'
= will_paginate @runs

app/views/runs/new.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <h3>Add a run</h3>
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
  $('select').material_select();
})
</script>

app/views/runs/show.html.erb
<div class="card">
  <p>Distance: <%= convert_meters_to_miles(@run.total_distance, 2) %> miles</p>
  <p>Time: <%= convert_seconds(@run.total_time, "minutes") %> minutes</p>
<hr>
<%= render 'run_map' %>
<br>
</div>