config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
    }
  resources :splash, only: [:index]
  resources :home, only: [:index, :update]
  resources :users do
    resources :runs
    resources :goals
  end

  devise_scope :user do
   get '/sign_up/:goal_id', to: 'registrations#new', as: :new_invite
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :users, :through => :races
  has_many :races
  has_many :runs

  validates_presence_of :name
  validates_presence_of :start_location
  validates_presence_of :end_location

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @user = current_user
    if params[:search_term]
      @goals = @user.goals.basic_search(params[:search_term]).includes(:runs, :races, :users)
    else
      @goals = @user.goals.all.paginate(:page => params[:page], :per_page => 6).includes(:runs, :races, :users)
    end

    respond_to do |format|
      format.js
      format.html {render :index}
    end
  end

  def show
    @goal = Goal.find(params[:id])

    @users_races_hash = @goal.users.map do |user|
      Hash["name" => user.name, "distance" => user.races.where(goal_id: @goal.id).first.progress]
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    # collect user input and make calls to GMaps geotagging
    user_total_distance = Geocoder.get_distance(Geocoder.get_geo(goal_params[:start_location]), Geocoder.get_geo(goal_params[:end_location]))

    if user_total_distance['rows'][0]['elements'][0].key?('distance')
      user_total_distance = user_total_distance['rows'][0]['elements'][0]['distance']['value']
      @goal = Goal.new({name: goal_params[:name],
                        start_location: goal_params[:start_location],
                        end_location: goal_params[:end_location],
                        start_latlng: Geocoder.get_geo(goal_params[:start_location]),
                        end_latlng: Geocoder.get_geo(goal_params[:end_location]),
                        total_distance: user_total_distance})
      @goals = Goal.all.collect{|goal| [goal.name, goal.id]}

      if @goal.save
        # create user_goal join

        current_user.races.create(goal_id: @goal.id, progress: 0)
        @flash_message = "You saved #{@goal.name}"

        if params[:opponents] != ''
          invite_opponents(params[:opponents].split(", "))
        end

        flash[:notice] = @flash_message
        redirect_to user_goal_path(current_user,@goal)
      else
        flash[:alert] = @goal.errors.full_messages.each {|m| m.to_s}.join
        render :new
      end
    else
      flash[:alert] = "No running directions found."
      @goal = Goal.new
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    @goals = current_user.goals.collect{|goal| [goal.name, goal.id]}

  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      flash[:notice] = "You edited #{@goal.name}"
      redirect_to user_goals_path(current_user)
    else
      flash[:alert] = @goal.errors.full_messages.each {|m| m.to_s}.join
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    if @goal.users.count > 1
      @goal.users.delete(current_user)
    else
      @goal.destroy
    end

    flash[:notice] = "You deleted #{@goal.name}"
    redirect_to user_goals_path(current_user)
  end

  private

  def goal_params
    if params[:search_term]
    else
      params.require(:goal).permit(:start_location, :end_location, :name, :total_distance, :ajax_flag)
    end
  end

  def invite_opponents(opponents)
    opponents.each do |invited_opponent|
      stripped_opponent = invited_opponent.strip

      if User.exists?(email: stripped_opponent)
        invited_user = User.find_by(email: stripped_opponent)
        invited_user.races.create(user_id: invited_user.id, goal_id: @goal.id, progress: 0)
        Mailer.race_invite(current_user, invited_user, @goal).deliver
      else
        invited_user = User.new(email: stripped_opponent)
        Mailer.new_user_invite(current_user, invited_user, @goal).deliver
      end
      @flash_message += "\n"+"and invited " + invited_user.email
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
  def calc_percent(user, goal)
    if goal.total_distance > 0
      percent = (user.races.where(goal_id: goal.id).first.progress / goal.total_distance *
       100).to_i
       if percent <= 100
         percent.to_s.concat("%")
       else
         "100%"
       end
     else
       "0%"
     end
  end

  def progress_color(percent)
    percent = percent.to_i
    if percent < 11
      "very-low"
    elsif percent < 26
      "low"
    elsif percent < 51
      "medium"
    elsif percent < 76
      "high"
    elsif percent < 100
      "very-high"
    else
      "chicken-dinner"
    end
  end
end

app/views/goals/_form.slim
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&libraries=places"

.card.grey.lighten-4
  .card-content.black-text
    = form_for [current_user, @goal] do |f|
      = f.label :name
      = f.text_field :name

      = f.label "Enter a start location for Google maps (ex: Steel Bridge, Portland)"
      = f.text_field :start_location, required: true
      = f.label "Enter an end location for Google maps (ex: Ross Island Bridge, Portland)"
      = f.text_field :end_location, required: true

      = label_tag "Invite opponents by email (separate opponents with commas)"
      = text_field_tag :opponents

      = f.submit class: 'btn'

javascript:
  function initialize_start() {
    var input = document.getElementById('goal_start_location');
    var autocomplete = new google.maps.places.Autocomplete(input);
  }
  function initialize_end() {
    var input = document.getElementById('goal_end_location');
    var autocomplete = new google.maps.places.Autocomplete(input);
  }
  google.maps.event.addDomListener(window, 'load', initialize_start);
  google.maps.event.addDomListener(window, 'load', initialize_end);

app/views/goals/_goal.slim
- @goals.order(:name).each do |goal|
  .col.l4.m6.s12
    .card.goal-card
      .card-content
        span.card-title.black-text
          = goal.name
        p
          | Total Distance:&nbsp
          = convert_meters_to_miles(goal.total_distance, 1)
          |  miles
        p.ellipsis
          | Starting Location:&nbsp
          = goal.start_location
        p.ellipsis
          | Ending Location:&nbsp
          = goal.end_location
        br
        p
          = link_to "View Details", user_goal_path(current_user.id, goal.id)
          | &nbsp
          | &nbsp
          = link_to "Delete", user_goal_path(current_user.id, goal.id),:data => {:confirm => "Are you sure?", :method => "delete"}
      .card-action
        - goal.users.each do |user|
          p
            = link_to user.name, user_runs_path(user.id)
            i.material-icons
              | directions_run
            | &nbsp
            span.percent
              | progress:&nbsp
              = calc_percent(user, goal)
          .progress
            <div class="progress-bar" style="width: #{width =calc_percent(user, goal)}" id="#{ progress_color(width) }">
            </div>

app/views/goals/_goal_map.slim
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&callback=initMap&libraries=geometry"


.preloader.valign-wrapper
  = render "preloader"
.thing
  .row.map-container
    .col.s8#map

javascript:
  $(document).ready(function(){
    $(".preloader").show();

    initMap();
  });

  function initMap() {
    var directionsService = new google.maps.DirectionsService;
    var directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers: true});
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 7
    });

    calculateAndDisplayRoute(directionsService, directionsDisplay);
    directionsDisplay.setMap(map);
    directionsDisplay.setPanel(document.getElementById('directions'));
  }

  function calculateAndDisplayRoute(directionsService, directionsDisplay) {
    directionsService.route({
      origin: '#{ @goal['start_location'] }',
      destination: '#{ @goal['end_location'] }',
      travelMode: 'WALKING'

    }, function(response, status) {
      if (status === 'OK') {

        directionsDisplay.setDirections(response);

        turnByTurnData = createDistanceArray(response);
        setMarker(turnByTurnData);

      } else {
           window.alert('Directions request failed due to ' + status);
      }
    });
  }

  function createDistanceArray(response){
    var turnByturnDistances = [];
    var distanceFromOrigin = 0;

    response.routes[0].legs[0].steps.map(function(step){
      distanceFromOrigin += step.distance.value;
      turnByturnDistances.push({
        "dist": step.distance.value,
        "lat_lng": {lat: step.lat_lngs[0].lat(), lng: step.lat_lngs[0].lng()},
        "total_dist": distanceFromOrigin});
    })
    return turnByturnDistances
  }

  function setMarker(turnByTurnData){
    var usersProgressArray = #{ @users_races_hash.to_json.html_safe };
    var nearestPointsArray = usersProgressArray.map(setNearestPoint);

    var markers = nearestPointsArray.map(function(nearestPoint){
      return new google.maps.Marker({
        position: nearestPoint["point"],
        map: map,
        label: nearestPoint["name"][0]
      });
    });

    var markerCluster = new MarkerClusterer(map, markers);
    $(".preloader").hide()

  }

  function setNearestPoint(userProgress){
    if (userProgress['distance'] >= _.last(turnByTurnData)['total_dist']){
      var nearestPoint = _.last(turnByTurnData)['lat_lng']
    }
    else {
      var nearestPoint = turnByTurnData.find(function findPoint(step){
        var progressAtStep = userProgress['distance'];

        return step.total_dist >= progressAtStep
      }).lat_lng;
    }
    return {"point": nearestPoint, "name": userProgress['name']};
  };

app/views/goals/_preloader.slim
.wheel
  .preloader-wrapper.big.active
    .spinner-layer.spinner-blue
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle
    .spinner-layer.spinner-red
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle
    .spinner-layer.spinner-yellow
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle
    .spinner-layer.spinner-green
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle

app/views/goals/create.js.erb
$('.goal-modal').remove();
$('#run_goal_id').append('<option value="<%= @goal.id %>"><%= @goal.name %></option>');
$('body').append(`<div class="alert alert-notice">
                    <%= image_tag 'x.png', class: 'x' %>
                    <h6 class="message" >Nice work. You added <%= @goal.name %> as a goal.</h6>`);
$('.alert').click(function() {
  $('.alert').hide();
});
$(document).ready(function(){
  $('select').material_select();

})

app/views/goals/edit.html.slim
h3 Edit your goal
= render 'form'

app/views/goals/edit.slim
h3 Edit your goal
= render 'form'

app/views/goals/index.js.erb
$('.goals').html("<%= j render 'goal' %>")

app/views/goals/index.slim
h3.center
  = @user.name
  |'s goals
.row
  .col.m4.s12.right
    h6
      | Filter goals
    = form_tag user_goals_path(current_user), method: 'get', remote: true do
      = label_tag 'Search Term'
      = text_field_tag :search_term
      = submit_tag 'Search', class: "btn left"
    = link_to "Show all", user_goals_path(current_user), method: 'get', remote: true, class: 'btn blue-grey darken-4', id: 'show-all'


- if @user == current_user
  .row
    .col.m4.s12
      =link_to "Add a Goal", new_user_goal_path(@user), class: "btn", data: { turbolinks: false }

.row
  .goals
    = render 'goal'
= will_paginate @goals

app/views/goals/new.js.erb
$('.goal-modal').html("<%= j render('form', @ajax_flag => false) %>")

app/views/goals/new.slim
.row
  .col.s6.offset-s3
    h3 Add a goal
    = render 'form'

app/views/goals/show.slim
.col.s12
  .card
    .card-content
      span.card-title = @goal.name
      .row
        .col.l4.s12
          p
            | Total Distance:&nbsp
            = convert_meters_to_miles(@goal.total_distance, 1)
            | miles
          p.ellipsis
            | Starting Location:&nbsp
            = @goal.start_location
          p.ellipsis
            | Ending Location:&nbsp
            = @goal.end_location
          br
          hr
          br
          - @goal.users.each do |user|
              p
                = link_to user.name, user_runs_path(user.id)
                i.material-icons
                  directions_run
                | &nbsp
                span.percent
                  | progress:&nbsp
                  = calc_percent(user, @goal)
              .progress
                <div class="progress-bar" style="width: #{ width =calc_percent(user, @goal) }" id="#{ progress_color(width) }"></div>

        .col.l8.s12.right
          = render 'goal_map'