config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
    }
  resources :splash, only: [:index]
  resources :home, only: [:index, :update]
  resources :users do
    resources :runs
    resources :goals
  end

  devise_scope :user do
   get '/sign_up/:goal_id', to: 'registrations#new', as: :new_invite
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RaceMe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <div class="nav-margin">
          <%= link_to image_tag("icon.jpg", class: 'brand-logo'), root_path %>
          <ul id="nav-mobile" class="hide-on-med-and-down right">
            <% if current_user %>
              <li><%= link_to 'Runs', user_runs_path(current_user) %></li>
              <li><%= link_to 'Goals', user_goals_path(current_user.id) %></li>
              <li>
                <%= link_to "Log out #{current_user.name}", destroy_user_session_path, method: 'delete' %>
              </li>
            <% else %>
              <li>
                <%- resource_class.omniauth_providers.each do |provider| %>
                  <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
                <% end -%>
              </li>
            <% end %>
          </ul>
          <ul id="slide-out" class="side-nav">
            <% if current_user %>
              <% if current_user.token %>
              <li class="auth-status">Authenticated with Strava</li>
              <% else %>
              <li><%= link_to 'Sign into Strava', "https://www.strava.com/oauth/authorize?client_id=#{ENV['CLIENT_ID']}&response_type=code&redirect_uri=http#{ENV['REDIRECT_URI']}/token_exchange" %></li>
              <% end %>
            <li><%= link_to 'View Runs', user_runs_path(current_user) %></li>
            <li><%= link_to 'View Goals', user_goals_path(current_user.id) %></li>
            <li><%= link_to "Log out #{current_user.name}", destroy_user_session_path, method: 'delete' %></li>
            <% else %>
            <li><%= link_to 'Log In', new_user_session_path %>  </li>
            <% end %>
          </ul>
          <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <% if value.present? %>
        <div class="alert alert-<%= key %>">
          <%= image_tag 'x.png', class: 'x' %>
          <h6 class="message"><%= value %></h6>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>